variables:
  CI_IMAGE_TAG: 'opengl'

stages:
  - test
  - postprocess

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/common.yml'

test:v0.7:
  stage: test
  image: "juliagpu/julia:v0.7-${CI_IMAGE_TAG}"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg3.jl#325
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.checkout(\"AbstractPlotting\");
                          Pkg.build();
                          Pkg.test(; coverage=false);'
  artifacts:
    when: always
    paths:
      - Manifest.toml
      - .julia/
      - deps/ext.jl
      - deps/build.log
      # gitlab-runner#2620
      - src/*.cov
      - src/*/*.cov
      - src/*/*/*.cov
