variables:
  JULIA_PKGDIR: "$CI_PROJECT_DIR/.julia/"
  package: 'Makie'

.test_template: &test_definition
  before_script:
    - apt-get -qq update
    # glfw
    - apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev
    # cairo etc
    - apt-get install -y gettext libpango1.0-0 libcairo2 libmagickwand-6.q16-2 libfontconfig1

  script:
    - julia -e 'Pkg.init();Pkg.clone("https://github.com/JuliaPlots/AbstractPlotting.jl.git")'
    # actual testing
    - julia -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$package\"));
                Pkg.resolve();
                Pkg.build(\"$package\");
                Pkg.test(\"$package\")"

test:0.6:
  image: juliagpu/julia:v0.6-opengl
  <<: *test_definition
