## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1
notifications:
  email: false
git:
  depth: 99999999
cache:
  directories:
    - $HOME/.julia/
